### ISSUE TITLE
Konami games won't load

### ISSUE THREAD

**Issue by duduke** [libretro/libretro-fba#12]
Trying to load mystwarr.zip on the latest buildbot version (5-5-2015) crashes and spits out:
RetroArch [ERROR] :: rarch_log_libretro :: [libretro ERROR] :: [FBA] Cannot find driver.

Although mystwarr appears in the gamelist.txt.

**Comment by barbudreadmon** [comment]
No issue here, you sure you have the latest (complete) romset ? mame/fba roms often relies on other zip files from the romset containing bioses.

**Comment by duduke** [comment]
I have the MAME 0.161 romset.
Do you know if I need anything other then the mystwarr.zip (like a BIOS or something)?
BTW, using the new MAME core it works, but I need FBA.

**Comment by barbudreadmon** [comment]
Try with a fba 0.2.97.36 romset ?

**Comment by duduke** [comment]
It works with the standalone windows FBA 0.2.97.36.
it doesn't work with the libretro-fba core...

**Comment by barbudreadmon** [comment]
As i said, mystwarr.zip is working (with the usual konami color issues on libretro-fba) on libretro-fba. If you don't want to get/build a fba 0.2.97.36 romset, i can't help you.

**Comment by barbudreadmon** [comment]
Ok, i just found out, didn't notice you said "buildbot version", obviously you are using fba-libretro (the old repo which is included in buildbot) instead of libretro-fba (this new repo synced with current fba version, which is not included in buildbot). Either build your core yourself or go ask the buildbot maintainers to add this repo to buildbot. I'm closing since your issue is not even related to this repo.
