### ISSUE TITLE
Dip switches as core options

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-fba#45]
@AkimanBengus do you think you can add dip switches to core options and name them correctly depending on the game?

**Comment by AkimanBengus** [comment]
Hello @fr500 , are you reading in my mind? :-)
I'm working on it for 2 weeks and I have quite finish.
I will normally commit today or tomorrow.

**Comment by fr500** [comment]
Hah amazing

**Comment by AkimanBengus** [comment]
Hello @fr500, I just committed the DIP Switch implementation.
If you have time, is it possible for you to test it with some of your favorite games?
I already did some test with CPS1, CPS3, Neogeo and some other old games.
Thanks in advance

**Comment by fr500** [comment]
works great as far as I'm concerned!
were you familiar with the fba codebase already?

**Comment by barbudreadmon** [comment]
@AkimanBengus I just ported fba 0.2.97.37 to libretro-fba. Everything seems to be ok but feel free to check if i didn't mess with your commits over the past months.

**Comment by fr500** [comment]
seems the UNIBIOS mode doesn't work but DIPSWITCH UNIBIOS works

**Comment by barbudreadmon** [comment]
i noticed they added a new bios rom ( v2.bin => MVS USA ver. 5 (4 slot) ), not 100% sure i understood how @AkimanBengus 's new code is handling all those bioses but i tried to modify it anyway, did my last commit fix neogeo modes ?

**Comment by AkimanBengus** [comment]
I didn't try yet but it seems good to me.

**Comment by AkimanBengus** [comment]
@fr500 who said:
> were you familiar with the fba codebase already?

No I wasn't, I'm just trying to understand what's happening in the code and I compare a lot with the win32 stand alone version to reflect features as much as possible.
With the DIP Switch addition, some games work now like Red Earth (CPS3) but maybe others too.
This is because DIP switches initialize some flags that weren't before like cps3_dip, NeoSystem and region in megadrive.
So many small issues are maybe fixed thanks this :-)

I have 2 or 3 things in mind to implement that are quite finished:
- Use a combo input for the Diagnostic (ex: Start + L + R or Hold Start during 1 sec). I'm trying to get back the L3 button because I need as much buttons as possible for the next feature. The user will be able to choose the combo with a core option.
- Integrate some macro in input_descriptor like '3x Punch', '3 Kick' (CPS) and 'AB', 'CD', etc (NeoGeo) using L1, R1, L2, R2, L3, R3.
- Add analog support. For this I need more time to understand how it works but I was able to play 'Forgotten world' with a Xbox controller using the right analog stick.

**Comment by barbudreadmon** [comment]
Nice work again, thanks for the help :)

**Comment by bbhenry** [comment]
can someone explain how exactly can I get to the dip switch menu? I am on fba v 0.2.97.37. I can't seem to find it in CPS 1 2 or 3 games. The NeoGeo one works by the way.
